# Generated by Django 4.0.6 on 2022-07-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingmachine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vending_machine',
            name='itemInStock',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vending_machine',
            name='itemPrice',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
